apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: fullstack-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: parinaya12/my-frontend:latest
        ports:
        - containerPort: 80
