apiVersion: v1
kind: Service
metadata:
  name: nodejs-service
  namespace: fullstack-app
spec:
  selector:
    app: nodejs
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
