apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: fullstack-app
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mongo
  storageClassName: manual
